// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Service struct {
	ID        int32        `json:"id"`
	Name      string       `json:"name"`
	BaseUrl   string       `json:"base_url"`
	Prefixes  []string     `json:"prefixes"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}
