// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	DeleteService(ctx context.Context, name string) error
	GetAllServices(ctx context.Context) ([]Service, error)
	GetService(ctx context.Context, name string) (Service, error)
	GetServicesByPrefix(ctx context.Context, prefixes []string) ([]Service, error)
	RegisterService(ctx context.Context, arg RegisterServiceParams) (Service, error)
}

var _ Querier = (*Queries)(nil)
