// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: services.sql

package db

import (
	"context"

	"github.com/lib/pq"
)

const deleteService = `-- name: DeleteService :exec
DELETE FROM services WHERE name = $1
`

func (q *Queries) DeleteService(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteService, name)
	return err
}

const getAllServices = `-- name: GetAllServices :many
SELECT id, name, base_url, prefixes, created_at, updated_at FROM services ORDER BY name
`

func (q *Queries) GetAllServices(ctx context.Context) ([]Service, error) {
	rows, err := q.db.QueryContext(ctx, getAllServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BaseUrl,
			pq.Array(&i.Prefixes),
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getService = `-- name: GetService :one
SELECT id, name, base_url, prefixes, created_at, updated_at FROM services WHERE name = $1
`

func (q *Queries) GetService(ctx context.Context, name string) (Service, error) {
	row := q.db.QueryRowContext(ctx, getService, name)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		pq.Array(&i.Prefixes),
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServicesByPrefix = `-- name: GetServicesByPrefix :many
SELECT id, name, base_url, prefixes, created_at, updated_at FROM services WHERE $1 = ANY(prefixes) ORDER BY name
`

func (q *Queries) GetServicesByPrefix(ctx context.Context, prefixes []string) ([]Service, error) {
	rows, err := q.db.QueryContext(ctx, getServicesByPrefix, pq.Array(prefixes))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BaseUrl,
			pq.Array(&i.Prefixes),
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerService = `-- name: RegisterService :one
INSERT INTO services (name, base_url, prefixes)
VALUES ($1, $2, $3)
ON CONFLICT (name) DO UPDATE SET
    base_url = EXCLUDED.base_url,
    prefixes = EXCLUDED.prefixes,
    updated_at = NOW()
RETURNING id, name, base_url, prefixes, created_at, updated_at
`

type RegisterServiceParams struct {
	Name     string   `json:"name"`
	BaseUrl  string   `json:"base_url"`
	Prefixes []string `json:"prefixes"`
}

func (q *Queries) RegisterService(ctx context.Context, arg RegisterServiceParams) (Service, error) {
	row := q.db.QueryRowContext(ctx, registerService, arg.Name, arg.BaseUrl, pq.Array(arg.Prefixes))
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		pq.Array(&i.Prefixes),
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
